-- GENERATED by setup.sh from versions.lock — do not edit by hand.
-- Change MASON_REGISTRY in versions.lock (or run ./setup.sh --update) instead.
--
-- Pinning the registry snapshot freezes every LSP server, formatter, linter and
-- DAP adapter version. Without it, Mason silently upgrades all of them.
return {
	registry = "github:mason-org/mason-registry@2026-10-06-unique-device",
}
