return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	main = "nvim-treesitter.configs",
	opts = {
		auto_install = true,
		-- Highlight disabled: Neovim 0.12 provides built-in treesitter highlighting.
		-- nvim-treesitter's highlight module registers custom query predicates that
		-- are incompatible with Neovim 0.12's node lifecycle, causing nil node errors.
		highlight = { enable = false },
		indent = { enable = true },
		ensure_installed = {
			"bash",
			"c",
			"diff",
			"go",
			"html",
			"javascript",
			"jsdoc",
			"json",
			"jsonc",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"printf",
			"python",
			"query",
			"regex",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
		},
	},
}
